### ISSUE TITLE
Failed Formatting of Label for Part 2 - Device Registration - Step 2

### ISSUE THREAD

**Issue by BIGC7** [djaramil/esp32cam-workshop#10]
See image below... The label for part 2 has invalid formatting.

![image](https://user-images.githubusercontent.com/60854256/74110490-0bc83a00-4b5b-11ea-8a23-5550af079ed3.png)

**Comment by djaramil** [comment]
That was weird - I couldn't see what was wrong with that.   I had to literally re-type that step 2 for the formatting to get recognized by the MD interpreter.  Thanks for pointing that out.
