### ISSUE TITLE
Part 1 Board/Baud Selection Confusion

### ISSUE THREAD

**Issue by BIGC7** [djaramil/esp32cam-workshop#2]
In part 1 the tutorial begins with selecting the AI Thinker ESP32-CAM board, which does not require an explicit programming baud rate to be specified. However, a couple steps later the tutorial says to select a specific programming baud rate and shows that the ESP32 Wrover Module is selected rather than the AI Thinker. This can be a possible point of confusion for some hackers getting started.

**Comment by djaramil** [comment]
Fixed.  Good catch.
