### ISSUE TITLE
Broken Link in Part 1 - DHT - Step 3

### ISSUE THREAD

**Issue by BIGC7** [djaramil/esp32cam-workshop#9]
See image below... That link gives a 404 now.

![image](https://user-images.githubusercontent.com/60854256/74110085-76777680-4b57-11ea-86fa-75d858cec658.png)

**Comment by djaramil** [comment]
I re-did that whole part.  Please take a look again.  Should be good now.

**Comment by BIGC7** [comment]
Looks good to me!
